<?php
/**
 * Created by PhpStorm.
 * User: cbonfre
 * Date: 31/05/2019
 * Time: 10:17
 */

$message = [
    "fr" => [
        "baseRechercheParmi" => "Rechercher parmi les cours, les ressources, ...",
        "homeALaUne" => "À la une",
        "homeZoomSur" => "Zoom sur",
        "homeSelectionRessource" => "Une sélection de ressources",
        "homeLireSuite" => "Lire la suite",
        "homeInscrireNewsletter" => "S'inscrire à la newsletter",
        "homeValidNewsLetter" => "En validant votre inscription, vous acceptez que UNT mémorise et utilise votre adresse email dans le but de vous envoyer mensuellement sa lettre d’informations. Vous pouvez vous désinscrire à tout moment à l'aide du lien présent à la fin de chaque newsletter. ",
        "actualites" => "Actualités",
        "actualitesLireSuite" => "Lire la suite",
        "resultatsResultats" => "résultats",
        "resultatsPourVotreRecherche" => "pour votre recherche",
        "resultatsTrierPar" => "Tri décroissant par",
        "resultatsTriPertinence" => "Pertinence",
        "resultatsTriDate" => "Date de publication",
        "resultatsFacetteEstampillage" => "Estampillage UNT",
        "resultatsFacetteDisciplines" => "Discipline",
        "resultatsFacetteNiveaux" => "Niveau",
        "resultatsFacetteTypeRessource" => "Type de ressource",
        "resultatsErreurRequete" => "Une erreur est survenue, la requête peut être mal formée.",
        "resultatsElargirRecherche" => "Elargissez votre recherche",
        "carteNoticeAccederRessource" => "Accéder à la ressource",
        "carteNoticeAccederNotice" => "Accéder au descriptif",
        "noticeRetourRecherche" => "Retour aux résultats de recherche",
        "noticeDescription" => "Description",
        "noticeVotreAvis" => "Votre avis",
        "noticeAccederRessource" => "Accéder à la ressource",
        "noticePedagogie" => "Pédagogie",
        "noticeComplements" => "Compléments",
        "noticeCoursComplet" => "Cours complet",
        "noticeTypesPedagogiques" => "Types pédagogiques",
        "noticeNiveaux" => "Niveaux",
        "noticeObjectifsPedagogiques" => "Objectifs pédagogiques",
        "noticeActivitesInduites" => "Activités induites",
        "noticePropositionUtilisation" => "Proposition d'utilisation",
        "noticeDureeApprentissage" => "Durée d'apprentissage",
        "noticeLangueApprenant" => "Langue de l'apprenant",
        "noticePartagerSur" => "Partager la notice sur",
        "noticeUniversiteProductrice" => "Université productrice",
        "noticeEtablissementCoEditeur" => "Etablissement co-éditeurs",
        "noticeDisciplines" => "Disciplines",
        "noticeMotsClefs" => "Mots-clefs",
        "noticeFicheSuplomfr" => "Fiche SUPLOMFR",
        "noticeRessourcesLiees" => "Ressources liées",
        "noticeRecommandations" => "Recommandations",
        "noticeNExistePas" => "La notice recherchée n'existe pas.",
        "noticeRelationAPourPrerequis" => "A pour prérequis",
        "noticeRelationEstPrerequisDe" => "Est prérequis de",
        "noticeRelationContient" => "Contient",
        "noticeRelationEstPartieDe" => "Est partie de",
        "noticeRelationReference" => "Référence",
        "noticeRelationEstReferencePar" => "Est référencé par",
        "noticeRelationEstAssocieA" => "Est associé à",
        "ressourceVotreAvis" => "Votre avis",
        "ressourceNonAffichee" => "La ressource ne peut pas être affichée sur cette page.",
        "partners" => "Partners",
        "ourPartners" => "Our partners",
        "projects" => "Projets",
        "ourProjects" => "Nos projets",
        "projectsList" => "Liste de nos projets",
        "latestPosts" => "Les derniers articles"
    ],
    "en" => [
        "baseRechercheParmi" => "Search among courses, resources, ...",
        "homeALaUne" => "News",
        "homeZoomSur" => "Zoom on",
        "homeSelectionRessource" => "A selection of resources",
        "homeLireSuite" => "Read more",
        "homeInscrireNewsletter" => "Subscribe to the newsletter",
        "homeValidNewsLetter" => "By validating your registration, you agree that UNT remembers and uses your email address in order to send you its newsletter monthly. You can unsubscribe at any time using the link at the end of each newsletter.",
        "actualites" => "News",
        "actualitesLireSuite" => "Read more",
        "resultatsResultats" => "results",
        "resultatsPourVotreRecherche" => "for your query",
        "resultatsTrierPar" => "Descending sort by",
        "resultatsTriPertinence" => "Relevance",
        "resultatsTriDate" => "Publication date",
        "resultatsFacetteEstampillage" => "UNT stamping",
        "resultatsFacetteDisciplines" => "Discipline",
        "resultatsFacetteNiveaux" => "Level",
        "resultatsFacetteTypeRessource" => "Resource type",
        "resultatsErreurRequete" => "An error has occurred, the request may be malformed.",
        "resultatsElargirRecherche" => "Expand your search",
        "carteNoticeAccederRessource" => "Access the resource",
        "carteNoticeAccederNotice" => "Access the notice",
        "noticeRetourRecherche" => "Back to search results",
        "noticeDescription" => "Description",
        "noticeVotreAvis" => "Your opinion",
        "noticeAccederRessource" => "Access the resource",
        "noticePedagogie" => "Pedagogy",
        "noticeComplements" => "Complements",
        "noticeCoursComplet" => "Full course",
        "noticeTypesPedagogiques" => "Pedagogical types",
        "noticeNiveaux" => "Levels",
        "noticeObjectifsPedagogiques" => "Educational goals",
        "noticeActivitesInduites" => "Induced activities",
        "noticePropositionUtilisation" => "Proposed use",
        "noticeDureeApprentissage" => "Learning time",
        "noticeLangueApprenant" => "Language of the learner",
        "noticePartagerSur" => "Share the notice on",
        "noticeUniversiteProductrice" => "Producer University",
        "noticeEtablissementCoEditeur" => "Establishment co-editors",
        "noticeDisciplines" => "Disciplines",
        "noticeMotsClefs" => "Keywords",
        "noticeFicheSuplomfr" => "SUPLOMFR card",
        "noticeRessourcesLiees" => "Related Resources",
        "noticeRecommandations" => "Recommendations",
        "noticeNExistePas" => "The requested record does not exist.",
        "noticeRelationAPourPrerequis" => "Has for prerequisites",
        "noticeRelationEstPrerequisDe" => "Is a prerequisite of",
        "noticeRelationContient" => "Contains",
        "noticeRelationEstPartieDe" => "Is part of",
        "noticeRelationReference" => "Reference",
        "noticeRelationEstReferencePar" => "Is referenced by",
        "noticeRelationEstAssocieA" => "Is associated with",
        "ressourceVotreAvis" => "Your opinion",
        "ressourceNonAffichee" => "The resource can not be displayed on this page.",
        "partners" => "Partners",
        "ourPartners" => "Our partners",
        "projects" => "Projects",
        "ourProjects" => "Our projects",
        "projectsList" => "Projects list",
        "latestPosts" => "Latest posts"
    ]
];

define("APP_MESSAGE", $message);