fr:
  home:
    discoverProjects: "Découvrez nos projets"
    subscribeNewsletter: "S'inscrire à la newsletter"
    subscribeNewsletterAlt: "S'abonner à la newsletter"
    lireSuite: "Lire la suite"
    selectionRessource: "Une sélection de ressources"
    zoomSur: "Zoom sur"
    aLaUne: "À la une"
  baseRechercheParmi: "Rechercher parmi les cours, les ressources, ..."
  actualites: "Actualités"
  actualitesLireSuite: "Lire la suite"
  etablissementsMembres: "Établissements membres"
  resultats:
    resultats: "résultats"
    pourVotreRecherche: "pour votre recherche"
    trierPar: "Tri décroissant par"
    triPertinence: "Pertinence"
    triDate: "Date de publication"
    facetteEstampillage: "Estampillage UNT"
    facetteDisciplines: "Discipline"
    facetteNiveaux: "Niveau"
    facetteTypeRessource: "Type de ressource"
    erreurRequete: "Une erreur est survenue, la requête peut être mal formée."
    elargirRecherche: "Elargissez votre recherche"
  carteNoticeAccederRessource: "Accéder à la ressource"
  carteNoticeAccederNotice: "Accéder au descriptif"
  notice:
    retourRecherche: "Retour aux résultats de recherche"
    description: "Description"
    votreAvis: "Votre avis"
    accederRessource: "Accéder à la ressource"
    pedagogie: "Pédagogie"
    complements: "Compléments"
    coursComplet: "Cours complet"
    typesPedagogiques: "Types pédagogiques"
    niveaux: "Niveaux"
    objectifsPedagogiques: "Objectifs pédagogiques"
    activitesInduites: "Activités induites"
    propositionUtilisation: "Proposition d'utilisation"
    dureeApprentissage: "Durée d'apprentissage"
    langueApprenant: "Langue de l'apprenant"
    partagerSur: "Partager la notice sur"
    tniversiteProductrice: "Université productrice"
    etablissementCoEditeur: "Etablissement co-éditeurs"
    disciplines: "Disciplines"
    motsClefs: "Mots-clefs"
    ficheSuplomfr: "Fiche SUPLOMFR"
    ressourcesLiees: "Ressources liées"
    recommandations: "Recommandations"
    nExistePas: "La notice recherchée n'existe pas."
    relationAPourPrerequis: "A pour prérequis"
    relationEstPrerequisDe: "Est prérequis de"
    relationContient: "Contient"
    relationEstPartieDe: "Est partie de"
    relationReference: "Référence"
    relationEstReferencePar: "Est référencé par"
    relationEstAssocieA: "Est associé à"
  ressourceVotreAvis: "Votre avis"
  ressourceNonAffichee: "La ressource ne peut pas être affichée sur cette page."
  partners: "Partenaires"
  ourPartners: "Nos partenaires"
  projects: "Projets"
  ourProjects: "Nos projets"
  projectsList: "Liste de nos projets"
  latestPosts: "Les derniers articles"
  backToNews: "Retour aux actualités"
  readMore: "En savoir plus"
  knowMore: "En savoir plus"
  newsletterValid: "Merci de vous être abonné à la newsletter !"
  publishedOn: "Publié le"
  pagination:
    first: "Premier"
    last: "Dernier"
    previous: "Précédent"
    next: "Suivant"

en:
  home:
    discoverProjects: "Discover our projects"
    subscribeNewsletter: "Subscribe to the newsletter"
    subscribeNewsletterAlt: "Subscribe to the newsletter"
    zoomSur: "Zoom on"
    selectionRessource: "A selection of resources"
    lireSuite: "Read more"
    aLaUne: "News"
  baseRechercheParmi: "Search among courses, resources, ..."
  etablissementsMembres: "Member institutions"
  actualites: "News"
  actualitesLireSuite: "Read more"
  resultats:
    resultats: "results"
    pourVotreRecherche: "for your query"
    trierPar: "Descending sort by"
    triPertinence: "Relevance"
    triDate: "Publication date"
    facetteEstampillage: "UNT stamping"
    facetteDisciplines: "Discipline"
    facetteNiveaux: "Level"
    facetteTypeRessource: "Resource type"
    erreurRequete: "An error has occurred, the request may be malformed."
    elargirRecherche: "Expand your search"
  carteNoticeAccederRessource: "Access the resource"
  carteNoticeAccederNotice: "Access the notice"
  notice:
    retourRecherche: "Back to search results"
    description: "Description"
    votreAvis: "Your opinion"
    accederRessource: "Access the resource"
    pedagogie: "Pedagogy"
    complements: "Complements"
    coursComplet: "Full course"
    typesPedagogiques: "Pedagogical types"
    niveaux: "Levels"
    objectifsPedagogiques: "Educational goals"
    activitesInduites: "Induced activities"
    propositionUtilisation: "Proposed use"
    dureeApprentissage: "Learning time"
    langueApprenant: "Language of the learner"
    partagerSur: "Share the notice on"
    universiteProductrice: "Producer University"
    etablissementCoEditeur: "Establishment co-editors"
    disciplines: "Disciplines"
    motsClefs: "Keywords"
    ficheSuplomfr: "SUPLOMFR card"
    ressourcesLiees: "Related Resources"
    recommandations: "Recommendations"
    nExistePas: "The requested record does not exist."
    relationAPourPrerequis: "Has for prerequisites"
    relationEstPrerequisDe: "Is a prerequisite of"
    relationContient: "Contains"
    relationEstPartieDe: "Is part of"
    relationReference: "Reference"
    relationEstReferencePar: "Is referenced by"
    relationEstAssocieA: "Is associated with"
  ressourceVotreAvis: "Your opinion"
  ressourceNonAffichee: "The resource can not be displayed on this page."
  partners: "Partners"
  ourPartners: "Our partners"
  projects: "Projects"
  ourProjects: "Our projects"
  projectsList: "Projects list"
  latestPosts: "Latest posts"
  backToNews: "Back to the news page"
  readMore: "Read more"
  knowMore: "Know more"
  newsletterValid: "Thank you for subscribing to the newsletter !"
  publishedOn: "Published on"
  pagination:
    first: "First"
    last: "Last"
    previous: "Previous"
    next: "Next"